version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: env-docker-php-memcached

    redis:
      image: redis:alpine
      container_name: env-docker-php-redis

    mysql:
      image: mysql:8.0
      container_name: env-docker-php-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=main
        - MYSQL_USER=user
        - MYSQL_PASSWORD=secret
      ports:
        - "3306:3306"

    webserver:
      image: nginx:alpine
      container_name: env-docker-php-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: env-docker-php-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

